# page title
page_title                                : Falendar                                  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1670616883                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/falendar/id1670616883?uo=4 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Falendar                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple & Safe, Organize Your Schedules

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : the Dafeige                                
your_link                                 : https://app.thedafeige.com                     
your_city                                 :                                 
email_address                             : falendar@thedafeige.com
facebook_username                         :                                           
instagram_username                        : thedafeige
twitter_username                          :
github_username                           :
youtube_username                          :
weibo_username                            : thedafeige
xiaohongshu_userid                        : 62f447b7000000001f0176cf


# Feature List                            Edit, add or remove features to be presented.
# 图标来自fontawesome 5.15.4里的solid和brand
features                                  :

  - title                                 : SIMPLE
    description                           : No fancy appearance, only practical features.
    fontawesome_icon_name                 : th-large

  - title                                 : SAFE
    description                           : All data is saved in system calendar and contacts.
    fontawesome_icon_name                 : shield-alt

  - title                                 : CUSTOMIZABLE
    description                           : Custom repeat rules, end rules, up to 5 alerts.
    fontawesome_icon_name                 : sliders-h

  - title                                 : ORGANIZED
    description                           : Events, birthdays, anniversaries, due dates.
    fontawesome_icon_name                 : columns

  - title                                 : NON-GREGORIAN BIRTHDAYS
    description                           : Chinese, Islamic and Hebrew birthdays.
    fontawesome_icon_name                 : birthday-cake

  - title                                 : ALTERNATE CALENDAR & HOLIDAYS
    description                           : Support Chinese, Japanese, Buddhist, Islamic, Hebrew, Persian, Indian, Ethiopian, and Coptic calendars. \nSupport Chinese and Hebrew holidays.
    fontawesome_icon_name                 : globe



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
